apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-infra
  namespace: rook-ceph
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-infra
  namespace: rook-ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-infra
subjects:
- kind: ServiceAccount
  name: prometheus-infra
  namespace: monitoring
