apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-infra-config
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-infra-config
subjects:
- kind: ServiceAccount
  name: prometheus-infra
  namespace: monitoring
