apiVersion: v1
kind: Service
metadata:
    name: wordpress-mysql
    labels:
        app: wordpress
spec:
    ports:
        - port: 3306
    selector:
        app: wordpress
        tier: mysql
    clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mysql-pv-claim
    labels:
        app: wordpress
spec:
    storageClassName: rook-ceph-block
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: wordpress-mysql
    labels:
        app: wordpress
spec:
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: wordpress
                tier: mysql
        spec:
            containers:
                - image: mysql:5.6
                  name: mysql
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        value: changeme
                  ports:
                      - containerPort: 3306
                        name: mysql
                  volumeMounts:
                      - name: mysql-persistent-storage
                        mountPath: /var/lib/mysql
            volumes:
                - name: mysql-persistent-storage
                  persistentVolumeClaim:
                      claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
    name: wordpress
    labels:
        app: wordpress
spec:
    ports:
        - port: 80
    selector:
        app: wordpress
        tier: frontend
    type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: wp-pv-claim
    labels:
        app: wordpress
spec:
    storageClassName: rook-ceph-block
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: wordpress
    labels:
        app: wordpress
spec:
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: wordpress
                tier: frontend
        spec:
            containers:
                - image: wordpress:5.1-php7.1-apache
                  name: wordpress
                  env:
                      - name: WORDPRESS_DB_HOST
                        value: wordpress-mysql
                      - name: WORDPRESS_DB_PASSWORD
                        value: changeme
                  ports:
                      - containerPort: 80
                        name: wordpress
                  volumeMounts:
                      - name: wordpress-persistent-storage
                        mountPath: /var/www/html
            volumes:
                - name: wordpress-persistent-storage
                  persistentVolumeClaim:
                      claimName: wp-pv-claim
